In [ ]:
'''
learn how to create repeatable result
'''

In [2]:
import numpy as np
import tensorflow as tf

In [49]:
# tf seed
tf.reset_default_graph() 
tf.set_random_seed(0)
# all we need is the above 2 lines in that order

a = tf.random_uniform([1])
with tf.Session() as sess:
  print(sess.run(a))  # generates 'A1'
  print(sess.run(a))  # generates 'A2'
  print(sess.run(b))

[ 0.32064009]
[ 0.012326]
[ 0.46133769]


In [46]:
# np seed
np.random.seed(0)
# all we need is the above line
print(np.random.permutation(10))
print(np.random.permutation(10))

[2 8 4 9 1 6 7 3 0 5]
[3 5 1 2 9 8 0 6 7 4]


In [52]:
a = tf.random_normal([2,2])
b = 1-a
with tf.Session() as sess1:
    print(sess1.run(b))

[[ 1.43046129 -0.22076154]
 [ 0.30155486  0.91023111]]
