In [1]:
'''
Idea:
First, test linearSVC
Then, test SVC with kernel
'''

'\nIdea:\nFirst, test linearSVC\nThen, test SVC with kernel\n'

In [34]:
# import
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.svm import LinearSVC, SVC
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score

In [3]:
# load data
iris = load_iris()
print(iris.DESCR)

Iris Plants Database

Notes
-----
Data Set Characteristics:
    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20  0.76     0.9565  (high!)
    ============== ==== ==== ======= ===== ====================

    :Missing Attribute Values: None
  

In [21]:
# shuffle
shuffle_ix = np.random.permutation(150)
X, y = iris.data[shuffle_ix], iris.target[shuffle_ix]
print(X.shape)
print(y.shape)
print(y)

(150, 4)
(150,)
[2 2 1 1 2 0 1 0 1 2 1 0 1 1 2 2 2 1 2 2 0 1 2 0 1 1 1 1 1 1 0 1 2 0 2 2 0
 0 1 0 0 2 0 1 1 2 0 1 0 0 1 0 0 1 1 2 1 0 0 1 2 2 1 2 1 1 0 1 2 1 0 2 2 0
 0 0 0 2 1 0 1 1 2 2 0 0 2 1 1 2 1 0 1 1 0 2 1 0 1 2 1 2 2 0 2 1 0 2 0 1 0
 0 2 2 1 1 2 2 0 1 2 1 0 0 0 2 2 1 2 0 0 2 2 0 0 1 2 0 0 0 2 2 2 2 0 0 2 1
 2 0]


In [5]:
# create LinearSVC
linearSVC = LinearSVC()

In [27]:
# evaluate
n_subsets = 3
linear_scores = cross_val_score(linearSVC, X, y=y, scoring="accuracy", cv = n_subsets)
print(linear_scores)
print(np.mean(linear_scores))

[ 0.92156863  0.96078431  0.95833333]
0.946895424837


In [37]:
# there is problem with the cross_val_score because the score is supposed to be nice because val_size = 50
# I guess it's because it's multiclass classification
X_train, X_test, y_train, y_test = X[:100], X[100:], y[:100], y[100:]
linearSVC.fit(X_train, y_train)
pred_test = linearSVC.predict(X_test)
print("Accuracy = ", accuracy_score(y_test, pred_test))

Accuracy =  0.96


In [7]:
# create polynomial SVC
PolySVC = SVC(kernel="poly")

In [8]:
# evaluate
poly_scores = cross_val_score(PolySVC, X, y, scoring="accuracy", cv=n_subsets)
print(poly_scores)
print(np.mean(poly_scores))

[ 0.96078431  0.98039216  0.95833333]
0.966503267974


In [9]:
# create rbf SVC
rbfSVC = SVC(kernel='rbf')

In [10]:
# evaluate
rbf_scores = cross_val_score(rbfSVC, X, y, scoring="accuracy", cv=n_subsets)
print(rbf_scores)
print(np.mean(rbf_scores))

[ 0.98039216  1.          0.97916667]
0.986519607843
